---
platform: linux
inputs:
- name: git-repo
outputs:
- name: distribution-repository
- name: git-repo
caches:
- path: maven
- path: gradle
params:
  BRANCH:
  CI: true
run:
  path: git-repo/ci/scripts/build-project.sh
